server:
  port: 1234
spring:
  datasource:
    initialize: true
    url: jdbc:h2:mem:testdb
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop